### ISSUE TITLE
Calling weatherbot-slack-outgoing-webhook.mybluemix.net fails

### ISSUE THREAD

**Issue by andreasnauerz** [jthomas/microservices_without_servers#3]
Calling https://weatherbot-slack-outgoing-webhook.mybluemix.net/?action=ACTION&namespace=NAMESPACE&apikey=APIKEY results in an error saying that the requested resource does not exist

**Comment by jthomas** [comment]
I've just realised this app got removed when Bluemix forced apps to move over the the Diego runtime. I have re-pushed the application, it *should* be working.

We should be able to remove the reliance on this proxy app now we have the `web-export` feature. I'll need to update the instructions.

**Comment by andreasnauerz** [comment]
Thanks.
Still not working; see details on Slack.

Am I right that the API_KEY has the format USERNAME:PASSWORD (from the weather company service credentials)? If so I have no clue what's still wrong :(

**Comment by andreasnauerz** [comment]
My fault; used the wrong API_KEY.
